[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "robot-link"
version = "0.1.0"
requires-python = ">=3.10"

[project.scripts]
robot-linkd = "robot_link.daemon:main"
robot-link-bone-server = "robot_link.bone_server:main"
robot-link-boned = "robot_link.bone_daemon:main"
robot-linkctl = "robot_link.bone_ctl:main"

[tool.setuptools]
packages = ["robot_link"]
